import timur from '../assets/images/Timur.jpeg';
import alina from '../assets/images/Alina.jpeg';
import ramil from '../assets/images/Ramil.jpg';
import ilana from '../assets/images/Ilana.jpeg';
import damil from '../assets/images/Damil.jpg';
import veronika from '../assets/images/Veronika.jpeg';
import alim from '../assets/images/Alim.jpeg';
import dariya from '../assets/images/Dariya.jpeg';
import emin from '../assets/images/Emin.jpg';
import nurali from '../assets/images/Nurali.png';
import maks from '../assets/images/Maks.jpg';
import mirhan from '../assets/images/Mirhan.jpeg';
import artur from '../assets/images/Artur.jpeg';
import nastya from '../assets/images/Nastya.jpeg';
import elina from '../assets/images/Elina.jpeg';
import daniil from '../assets/images/Daniil.jpeg';
import adema from '../assets/images/Adema.jpeg';
import dauren from '../assets/images/Dauren.jpeg';
import damir from '../assets/images/Damir.jpeg';
import ksusha from '../assets/images/Ksusha.jpeg';

const worksData = [
  {
    title: 'Абдиршин Тимур',
    shortDescription: '',
    clientName: 'https://www.youtube.com/embed/Bw9eW4uaHOA',
    projectValue: '',
    date: '',
    descriptionFirst: timur,
    descriptionSecond: '',
    mainImage: timur,
    exampleImageFirst: '',
    exampleImageSecond: '',
    link: '',
    id: 0,
  },
  {
    title: 'Албакова Алина',
    shortDescription: '',
    clientName: 'https://www.youtube.com/embed/-6PwAYvzse8',
    projectValue: '',
    date: '',
    descriptionFirst: alina,
    descriptionSecond: '',
    mainImage: alina,
    exampleImageFirst: '',
    exampleImageSecond: '',
    link: '',
    id: 1,
  },
  {
    title: 'Ашрафулин Рамиль',
    shortDescription: '',
    clientName: 'https://youtube.com/shorts/dzkO56MAB70?feature=share',
    projectValue: 'video',
    date: '',
    descriptionFirst: ramil,
    descriptionSecond: '',
    mainImage: ramil,
    exampleImageFirst: '',
    exampleImageSecond: '',
    link: '',
    id: 2,
  },
  {
    title: 'Байниетова Илана',
    shortDescription: '',
    clientName: 'https://www.youtube.com/embed/zO9LDHjix1w',
    projectValue: '',
    date: '',
    descriptionFirst: ilana,
    descriptionSecond: '',
    mainImage: ilana,
    exampleImageFirst: '',
    exampleImageSecond: '',
    link: '',
    id: 3,
  },
  {
    title: 'Бердыев Дамиль',
    shortDescription: '',
    clientName: 'https://www.youtube.com/embed/R6mHZ2OMnz8',
    projectValue: '',
    date: '',
    descriptionFirst: damil,
    descriptionSecond: '',
    mainImage: damil,
    exampleImageFirst: '',
    exampleImageSecond: '',
    link: '',
    id: 19,
  },
  {
    title: 'Бушуева Вероника',
    shortDescription: '',
    clientName: 'https://www.youtube.com/embed/LdE0f71-siY',
    projectValue: '',
    date: '',
    descriptionFirst: veronika,
    descriptionSecond: '',
    mainImage: veronika,
    exampleImageFirst: '',
    exampleImageSecond: '',
    link: '',
    id: 4,
  },
  {
    title: 'Диханбаев Алим',
    shortDescription: '',
    clientName: 'https://www.youtube.com/embed/Wdc_BBa-HrM',
    projectValue: '',
    date: '',
    descriptionFirst: alim,
    descriptionSecond: '',
    mainImage: alim,
    exampleImageFirst: '',
    exampleImageSecond: '',
    link: '',
    id: 5,
  },
  {
    title: 'Исимбаева Дария',
    shortDescription: '',
    clientName: 'https://www.youtube.com/embed/H6EjwLn6Qyc',
    projectValue: '',
    date: '',
    descriptionFirst: dariya,
    descriptionSecond: '',
    mainImage: dariya,
    exampleImageFirst: '',
    exampleImageSecond: '',
    link: '',
    id: 6,
  },
  {
    title: 'Кадырбаев Эмин',
    shortDescription: '',
    clientName: 'https://www.youtube.com/embed/T3R1KWY80Zo',
    projectValue: '',
    date: '',
    descriptionFirst: emin,
    descriptionSecond: '',
    mainImage: emin,
    exampleImageFirst: '',
    exampleImageSecond: '',
    link: '',
    id: 7,
  },
  {
    title: 'Калханов Нурали',
    shortDescription: '',
    clientName: 'https://www.youtube.com/embed/laa77xWDnik',
    projectValue: '',
    date: '',
    descriptionFirst: nurali,
    descriptionSecond: '',
    mainImage: nurali,
    exampleImageFirst: '',
    exampleImageSecond: '',
    link: '',
    id: 8,
  },
  {
    title: 'Малютин Максим',
    shortDescription: '',
    clientName: 'https://www.youtube.com/embed/lu8G-gA9WcM',
    projectValue: '',
    date: '',
    descriptionFirst: maks,
    descriptionSecond: '',
    mainImage: maks,
    exampleImageFirst: '',
    exampleImageSecond: '',
    link: '',
    id: 9,
  },
  {
    title: 'Мирхаят Мирхан',
    shortDescription: '',
    clientName: 'https://www.youtube.com/embed/FhjHJ05-d40',
    projectValue: '',
    date: '',
    descriptionFirst: mirhan,
    descriptionSecond: '',
    mainImage: mirhan,
    exampleImageFirst: '',
    exampleImageSecond: '',
    link: '',
    id: 10,
  },
  {
    title: 'Музбулаков Артур',
    shortDescription: '',
    clientName: 'https://www.youtube.com/embed/7b89Y1OX2oM',
    projectValue: '',
    date: '',
    descriptionFirst: artur,
    descriptionSecond: '',
    mainImage: artur,
    exampleImageFirst: '',
    exampleImageSecond: '',
    link: '',
    id: 11,
  },
  {
    title: 'Пак Анастасия',
    shortDescription: '',
    clientName: 'https://www.youtube.com/embed/r-Wk5lWv6ao',
    projectValue: '',
    date: '',
    descriptionFirst: nastya,
    descriptionSecond: '',
    mainImage: nastya,
    exampleImageFirst: '',
    exampleImageSecond: '',
    link: '',
    id: 12,
  },
  {
    title: 'Пак Элина',
    shortDescription: '',
    clientName: 'https://www.youtube.com/embed/JzGB2X53sg0',
    projectValue: '',
    date: '',
    descriptionFirst: elina,
    descriptionSecond: '',
    mainImage: elina,
    exampleImageFirst: '',
    exampleImageSecond: '',
    link: '',
    id: 13,
  },
  {
    title: 'Розенгоф Даниил',
    shortDescription: '',
    clientName: 'https://www.youtube.com/embed/DBpcFsnhMtw',
    projectValue: '',
    date: '',
    descriptionFirst: daniil,
    descriptionSecond: '',
    mainImage: daniil,
    exampleImageFirst: '',
    exampleImageSecond: '',
    link: '',
    id: 14,
  },
  {
    title: 'Толеген Адема',
    shortDescription: '',
    clientName: 'https://www.youtube.com/embed/v522BzbupnA',
    projectValue: '',
    date: '',
    descriptionFirst: adema,
    descriptionSecond: '',
    mainImage: adema,
    exampleImageFirst: '',
    exampleImageSecond: '',
    link: '',
    id: 15,
  },
  {
    title: 'Турарбек Даурен',
    shortDescription: '',
    clientName: 'https://www.youtube.com/embed/YutlpzMPBgM',
    projectValue: '',
    date: '',
    descriptionFirst: dauren,
    descriptionSecond: '',
    mainImage: dauren,
    exampleImageFirst: '',
    exampleImageSecond: '',
    link: '',
    id: 16,
  },
  {
    title: 'Шарипов Дамир',
    shortDescription: '',
    clientName: 'https://www.youtube.com/embed/ILoRrAu-8PE',
    projectValue: '',
    date: '',
    descriptionFirst: damir,
    descriptionSecond: '',
    mainImage: damir,
    exampleImageFirst: '',
    exampleImageSecond: '',
    link: '',
    id: 17,
  },
  {
    title: 'Югай Оксана',
    shortDescription: '',
    clientName: 'https://www.youtube.com/embed/Pn0_YbGvuq4',
    projectValue: '',
    date: '',
    descriptionFirst: ksusha,
    descriptionSecond: '',
    mainImage: ksusha,
    exampleImageFirst: '',
    exampleImageSecond: '',
    link: '',
    id: 18,
  },
];

export default worksData;
